kind: AdmissionConfiguration
apiVersion: apiserver.config.k8s.io/v1
plugins:
    - name: PodSecurity
      configuration:
        kind: PodSecurityConfiguration
        apiVersion: pod-security.admission.config.k8s.io/v1beta1
        defaults:
            enforce-version: v1.24
            audit: restricted
            audit-version: v1.24
            warn: restricted
            warn-version: v1.24
        exemptions:
            namespaces:
                - kube-system
                - tkg-system
