namespace: external-dns
deployment:
  args:
    - --registry=txt
    - --txt-prefix=external-dns-
    - --txt-owner-id=tanzu
    - --provider=rfc2136
     - --provider=sync
    - --rfc2136-host=192.168.70.10
    - --rfc2136-port=53
    - --rfc2136-zone=djdlab.net
    - --rfc2136-insecure
    - --rfc2136-tsig-axfr
    - --source=service
    - --source=contour-httpproxy
    - --source=ingress
    - --domain-filter=djdlab.net